app = "kanban-rikard"
primary_region = "arn"

[build]

[env]
  ConnectionStrings__DefaultConnection = "Data Source=/data/kanban.db"

[[mounts]]
  source = "kanban_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
